name: Build

on:
  push:
  workflow_dispatch:

jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build plugin
        run: mvn -B package
        working-directory: plugin
      - uses: actions/upload-artifact@v4
        with:
          name: ManiacLobby-plugin
          path: plugin/target/ManiacLobby-1.0.0.jar

  mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12
      - name: Build mod
        run: gradle build
        working-directory: mod
      - uses: actions/upload-artifact@v4
        with:
          name: ManiacLobby-mod
          path: mod/build/libs/*.jar
